---
title: "COOP"
author: "Gabriel Campos"
date: "11/22/2020"
output:
    pdf_document: default
#html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(openintro)
library(DATA606)
library(zoo)
library(lubridate)
library(ggplot2)
library(readxl)
Unemp <- read_excel("D:/Bulk Data/COOP_Project_Data/USUnemployment.xlsx")
#View(USUnemployment)
```

```{r,echo=FALSE}
y48<-Unemp %>% 
  rownames_to_column() %>% 
  filter(Year == 1948)%>%
  gather(variable, value, -rowname) %>% 
  spread(rowname, value)
colnames(y48) <- c("Month", "Unemployment Rate")
y48<-cbind(Year=1948,y48)
y48<-y48[-c(1,14),]
y48<-y48[order(match(y48$Month, month.abb)), ]
y48$Month<-factor(y48$Month,levels = month.abb)
```

```{r,echo=FALSE}

y49<-Unemp %>% 
  rownames_to_column() %>% 
  filter(Year == 1949)%>%
  gather(variable, value, -rowname) %>% 
  spread(rowname, value)
colnames(y49) <- c("Month", "Unemployment Rate")
y49<-cbind(Year=1949,y49)
y49<-y49[-c(1,14),]
y49<-y49[order(match(y49$Month, month.abb)), ]
y49$Month<-factor(y49$Month, levels = month.abb)
```

```{r,echo=FALSE}

y50<-Unemp %>% 
  rownames_to_column() %>% 
  filter(Year == 1950)%>%
  gather(variable, value, -rowname) %>% 
  spread(rowname, value)
colnames(y50) <- c("Month", "Unemployment Rate")
y50<-cbind(Year=1950,y50)
y50<-y50[-c(1,14),]
y50<-y50[order(match(y50$Month, month.abb)), ]
y50$Month<-factor(y50$Month, levels = month.abb)
```

```{r,echo=FALSE}

y51<-Unemp %>% 
  rownames_to_column() %>% 
  filter(Year == 1951)%>%
  gather(variable, value, -rowname) %>% 
  spread(rowname, value)
colnames(y51) <- c("Month", "Unemployment Rate")
y51<-cbind(Year=1951,y51)
y51<-y51[-c(1,14),]
y51<-y51[order(match(y51$Month, month.abb)), ]
y51$Month<-factor(y51$Month, levels = month.abb)
```

```{r,echo=FALSE}

y52<-Unemp %>% 
  rownames_to_column() %>% 
  filter(Year == 1952)%>%
  gather(variable, value, -rowname) %>% 
  spread(rowname, value)
colnames(y52) <- c("Month", "Unemployment Rate")
y52<-cbind(Year=1952,y52)
y52<-y52[-c(1,14),]
y52<-y52[order(match(y52$Month, month.abb)), ]
y52$Month<-factor(y52$Month, levels = month.abb)
```

```{r,echo=FALSE}

y53<-Unemp %>% 
  rownames_to_column() %>% 
  filter(Year == 1953)%>%
  gather(variable, value, -rowname) %>% 
  spread(rowname, value)
colnames(y53) <- c("Month", "Unemployment Rate")
y53<-cbind(Year=1953,y53)
y53<-y53[-c(1,14),]
y53<-y53[order(match(y53$Month, month.abb)), ]
y53$Month<-factor(y53$Month, levels = month.abb)
```

```{r,echo=FALSE}

y54<-Unemp %>% 
  rownames_to_column() %>% 
  filter(Year == 1954)%>%
  gather(variable, value, -rowname) %>% 
  spread(rowname, value)
colnames(y54) <- c("Month", "Unemployment Rate")
y54<-cbind(Year=1954,y54)
y54<-y54[-c(1,14),]
y54<-y54[order(match(y54$Month, month.abb)), ]
y54$Month<-factor(y54$Month, levels = month.abb)
```

```{r,echo=FALSE}

y55<-Unemp %>% 
  rownames_to_column() %>% 
  filter(Year == 1955)%>%
  gather(variable, value, -rowname) %>% 
  spread(rowname, value)
colnames(y55) <- c("Month", "Unemployment Rate")
y55<-cbind(Year=1955,y55)
y55<-y55[-c(1,14),]
y55<-y55[order(match(y55$Month, month.abb)), ]
y55$Month<-factor(y55$Month, levels = month.abb)
```

```{r,echo=FALSE}

y56<-Unemp %>% 
  rownames_to_column() %>% 
  filter(Year == 1956)%>%
  gather(variable, value, -rowname) %>% 
  spread(rowname, value)
colnames(y56) <- c("Month", "Unemployment Rate")
y56<-cbind(Year=1956,y56)
y56<-y56[-c(1,14),]
y56<-y56[order(match(y56$Month, month.abb)), ]
y56$Month<-factor(y56$Month, levels = month.abb)
```

```{r,echo=FALSE}

y57<-Unemp %>% 
  rownames_to_column() %>% 
  filter(Year == 1957)%>%
  gather(variable, value, -rowname) %>% 
  spread(rowname, value)
colnames(y57) <- c("Month", "Unemployment Rate")
y57<-cbind(Year=1957,y57)
y57<-y57[-c(1,14),]
y57<-y57[order(match(y57$Month, month.abb)), ]
y57$Month<-factor(y57$Month, levels = month.abb)
```

```{r,echo=FALSE}

y58<-Unemp %>% 
  rownames_to_column() %>% 
  filter(Year == 1958)%>%
  gather(variable, value, -rowname) %>% 
  spread(rowname, value)
colnames(y58) <- c("Month", "Unemployment Rate")
y58<-cbind(Year=1958,y58)
y58<-y58[-c(1,14),]
y58<-y58[order(match(y58$Month, month.abb)), ]
y58$Month<-factor(y58$Month, levels = month.abb)
```

```{r,echo=FALSE}

y59<-Unemp %>% 
  rownames_to_column() %>% 
  filter(Year == 1959)%>%
  gather(variable, value, -rowname) %>% 
  spread(rowname, value)
colnames(y59) <- c("Month", "Unemployment Rate")
y59<-cbind(Year=1959,y59)
y59<-y59[-c(1,14),]
y59<-y59[order(match(y59$Month, month.abb)), ]
y59$Month<-factor(y59$Month, levels = month.abb)
```

```{r,echo=FALSE}

y60<-Unemp %>% 
  rownames_to_column() %>% 
  filter(Year == 1960)%>%
  gather(variable, value, -rowname) %>% 
  spread(rowname, value)
colnames(y60) <- c("Month", "Unemployment Rate")
y60<-cbind(Year=1960,y60)
y60<-y60[-c(1,14),]
y60<-y60[order(match(y60$Month, month.abb)), ]
y60$Month<-factor(y60$Month, levels = month.abb)
```

```{r, echo=FALSE}

y61<-Unemp %>% 
  rownames_to_column() %>% 
  filter(Year == 1961)%>%
  gather(variable, value, -rowname) %>% 
  spread(rowname, value)
colnames(y61) <- c("Month", "Unemployment Rate")
y61<-cbind(Year=1961,y61)
y61<-y61[-c(1,14),]
y61<-y61[order(match(y61$Month, month.abb)), ]
y61$Month<-factor(y61$Month, levels = month.abb)
```

```{r, echo=FALSE}

y62<-Unemp %>% 
  rownames_to_column() %>% 
  filter(Year == 1962 )%>%
  gather(variable, value, -rowname) %>% 
  spread(rowname, value)
colnames(y62) <- c("Month", "Unemployment Rate")
y62<-cbind(Year= 1962 ,y62)
y62<-y62[-c(1,14),]
y62<-y62[order(match(y62$Month, month.abb)), ]
y62$Month<-factor(y62$Month, levels = month.abb)
```

```{r, echo=FALSE}

y63<-Unemp %>% 
  rownames_to_column() %>% 
  filter(Year == 1963 )%>%
  gather(variable, value, -rowname) %>% 
  spread(rowname, value)
colnames(y63) <- c("Month", "Unemployment Rate")
y63<-cbind(Year= 1963 ,y63)
y63<-y63[-c(1,14),]
y63<-y63[order(match(y63$Month, month.abb)), ]
y63$Month<-factor(y63$Month, levels = month.abb)
```

```{r, echo=FALSE}

y64<-Unemp %>% 
  rownames_to_column() %>% 
  filter(Year == 1964 )%>%
  gather(variable, value, -rowname) %>% 
  spread(rowname, value)
colnames(y64) <- c("Month", "Unemployment Rate")
y64<-cbind(Year= 1964 ,y64)
y64<-y64[-c(1,14),]
y64<-y64[order(match(y64$Month, month.abb)), ]
y64$Month<-factor(y64$Month, levels = month.abb)
```

```{r, echo=FALSE}

y65<-Unemp %>% 
  rownames_to_column() %>% 
  filter(Year == 1965 )%>%
  gather(variable, value, -rowname) %>% 
  spread(rowname, value)
colnames(y65) <- c("Month", "Unemployment Rate")
y65<-cbind(Year= 1965 ,y65)
y65<-y65[-c(1,14),]
y65<-y65[order(match(y65$Month, month.abb)), ]
y65$Month<-factor(y65$Month, levels = month.abb)
```

```{r, echo=FALSE}

y66<-Unemp %>% 
  rownames_to_column() %>% 
  filter(Year == 1966 )%>%
  gather(variable, value, -rowname) %>% 
  spread(rowname, value)
colnames(y66) <- c("Month", "Unemployment Rate")
y66<-cbind(Year= 1966 ,y66)
y66<-y66[-c(1,14),]
y66<-y66[order(match(y66$Month, month.abb)), ]
y66$Month<-factor(y66$Month, levels = month.abb)
```

```{r, echo=FALSE}

y67<-Unemp %>% 
  rownames_to_column() %>% 
  filter(Year == 1967 )%>%
  gather(variable, value, -rowname) %>% 
  spread(rowname, value)
colnames(y67) <- c("Month", "Unemployment Rate")
y67<-cbind(Year= 1967 ,y67)
y67<-y67[-c(1,14),]
y67<-y67[order(match(y67$Month, month.abb)), ]
y67$Month<-factor(y67$Month, levels = month.abb)
```

```{r, echo=FALSE}

y68<-Unemp %>% 
  rownames_to_column() %>% 
  filter(Year == 1968 )%>%
  gather(variable, value, -rowname) %>% 
  spread(rowname, value)
colnames(y68) <- c("Month", "Unemployment Rate")
y68<-cbind(Year= 1968 ,y68)
y68<-y68[-c(1,14),]
y68<-y68[order(match(y68$Month, month.abb)), ]
y68$Month<-factor(y68$Month, levels = month.abb)
```

```{r, echo=FALSE}

y69<-Unemp %>% 
  rownames_to_column() %>% 
  filter(Year == 1969 )%>%
  gather(variable, value, -rowname) %>% 
  spread(rowname, value)
colnames(y69) <- c("Month", "Unemployment Rate")
y69<-cbind(Year= 1969 ,y69)
y69<-y69[-c(1,14),]
y69<-y69[order(match(y69$Month, month.abb)), ]
y69$Month<-factor(y69$Month, levels = month.abb)
```

```{r, echo=FALSE}

y70<-Unemp %>% 
  rownames_to_column() %>% 
  filter(Year == 1970 )%>%
  gather(variable, value, -rowname) %>% 
  spread(rowname, value)
colnames(y70) <- c("Month", "Unemployment Rate")
y70<-cbind(Year= 1970 ,y70)
y70<-y70[-c(1,14),]
y70<-y70[order(match(y70$Month, month.abb)), ]
y70$Month<-factor(y70$Month, levels = month.abb)
```

```{r, echo=FALSE}

y71<-Unemp %>% 
  rownames_to_column() %>% 
  filter(Year == 1971 )%>%
  gather(variable, value, -rowname) %>% 
  spread(rowname, value)
colnames(y71) <- c("Month", "Unemployment Rate")
y71<-cbind(Year= 1971 ,y71)
y71<-y71[-c(1,14),]
y71<-y71[order(match(y71$Month, month.abb)), ]
y71$Month<-factor(y71$Month, levels = month.abb)
```

```{r, echo=FALSE}

y72<-Unemp %>% 
  rownames_to_column() %>% 
  filter(Year == 1972 )%>%
  gather(variable, value, -rowname) %>% 
  spread(rowname, value)
colnames(y72) <- c("Month", "Unemployment Rate")
y72<-cbind(Year= 1972 ,y72)
y72<-y72[-c(1,14),]
y72<-y72[order(match(y72$Month, month.abb)), ]
y72$Month<-factor(y72$Month, levels = month.abb)
```

```{r, echo=FALSE}

y73<-Unemp %>% 
  rownames_to_column() %>% 
  filter(Year == 1973 )%>%
  gather(variable, value, -rowname) %>% 
  spread(rowname, value)
colnames(y73) <- c("Month", "Unemployment Rate")
y73<-cbind(Year= 1973 ,y73)
y73<-y73[-c(1,14),]
y73<-y73[order(match(y73$Month, month.abb)), ]
y73$Month<-factor(y73$Month, levels = month.abb)
```

```{r, echo=FALSE}

y74<-Unemp %>% 
  rownames_to_column() %>% 
  filter(Year == 1974 )%>%
  gather(variable, value, -rowname) %>% 
  spread(rowname, value)
colnames(y74) <- c("Month", "Unemployment Rate")
y74<-cbind(Year= 1974 ,y74)
y74<-y74[-c(1,14),]
y74<-y74[order(match(y74$Month, month.abb)), ]
y74$Month<-factor(y74$Month, levels = month.abb)
```

```{r, echo=FALSE}

y75<-Unemp %>% 
  rownames_to_column() %>% 
  filter(Year == 1975 )%>%
  gather(variable, value, -rowname) %>% 
  spread(rowname, value)
colnames(y75) <- c("Month", "Unemployment Rate")
y75<-cbind(Year= 1975 ,y75)
y75<-y75[-c(1,14),]
y75<-y75[order(match(y75$Month, month.abb)), ]
y75$Month<-factor(y75$Month, levels = month.abb)
```

```{r, echo=FALSE}

y76<-Unemp %>% 
  rownames_to_column() %>% 
  filter(Year == 1976 )%>%
  gather(variable, value, -rowname) %>% 
  spread(rowname, value)
colnames(y76) <- c("Month", "Unemployment Rate")
y76<-cbind(Year= 1976 ,y76)
y76<-y76[-c(1,14),]
y76<-y76[order(match(y76$Month, month.abb)), ]
y76$Month<-factor(y76$Month, levels = month.abb)
```

```{r, echo=FALSE}

y77<-Unemp %>% 
  rownames_to_column() %>% 
  filter(Year == 1977 )%>%
  gather(variable, value, -rowname) %>% 
  spread(rowname, value)
colnames(y77) <- c("Month", "Unemployment Rate")
y77<-cbind(Year= 1977 ,y77)
y77<-y77[-c(1,14),]
y77<-y77[order(match(y77$Month, month.abb)), ]
y77$Month<-factor(y77$Month, levels = month.abb)
```

```{r, echo=FALSE}

y78<-Unemp %>% 
  rownames_to_column() %>% 
  filter(Year == 1978 )%>%
  gather(variable, value, -rowname) %>% 
  spread(rowname, value)
colnames(y78) <- c("Month", "Unemployment Rate")
y78<-cbind(Year= 1978 ,y78)
y78<-y78[-c(1,14),]
y78<-y78[order(match(y78$Month, month.abb)), ]
y78$Month<-factor(y78$Month, levels = month.abb)
```

```{r, echo=FALSE}

y79<-Unemp %>% 
  rownames_to_column() %>% 
  filter(Year == 1979 )%>%
  gather(variable, value, -rowname) %>% 
  spread(rowname, value)
colnames(y79) <- c("Month", "Unemployment Rate")
y79<-cbind(Year= 1979 ,y79)
y79<-y79[-c(1,14),]
y79<-y79[order(match(y79$Month, month.abb)), ]
y79$Month<-factor(y79$Month, levels = month.abb)
```

```{r, echo=FALSE}

y80<-Unemp %>% 
  rownames_to_column() %>% 
  filter(Year == 1980 )%>%
  gather(variable, value, -rowname) %>% 
  spread(rowname, value)
colnames(y80) <- c("Month", "Unemployment Rate")
y80<-cbind(Year= 1980 ,y80)
y80<-y80[-c(1,14),]
y80<-y80[order(match(y80$Month, month.abb)), ]
y80$Month<-factor(y80$Month, levels = month.abb)
```

```{r, echo=FALSE}

y81<-Unemp %>% 
  rownames_to_column() %>% 
  filter(Year == 1981 )%>%
  gather(variable, value, -rowname) %>% 
  spread(rowname, value)
colnames(y81) <- c("Month", "Unemployment Rate")
y81<-cbind(Year= 1981 ,y81)
y81<-y81[-c(1,14),]
y81<-y81[order(match(y81$Month, month.abb)), ]
y81$Month<-factor(y81$Month, levels = month.abb)
```

```{r, echo=FALSE}

y82<-Unemp %>% 
  rownames_to_column() %>% 
  filter(Year == 1982 )%>%
  gather(variable, value, -rowname) %>% 
  spread(rowname, value)
colnames(y82) <- c("Month", "Unemployment Rate")
y82<-cbind(Year= 1982 ,y82)
y82<-y82[-c(1,14),]
y82<-y82[order(match(y82$Month, month.abb)), ]
y82$Month<-factor(y82$Month, levels = month.abb)
```

```{r, echo=FALSE}

y83<-Unemp %>% 
  rownames_to_column() %>% 
  filter(Year == 1983 )%>%
  gather(variable, value, -rowname) %>% 
  spread(rowname, value)
colnames(y83) <- c("Month", "Unemployment Rate")
y83<-cbind(Year= 1983 ,y83)
y83<-y83[-c(1,14),]
y83<-y83[order(match(y83$Month, month.abb)), ]
y83$Month<-factor(y83$Month, levels = month.abb)
```

```{r, echo=FALSE}

y84<-Unemp %>% 
  rownames_to_column() %>% 
  filter(Year == 1984 )%>%
  gather(variable, value, -rowname) %>% 
  spread(rowname, value)
colnames(y84) <- c("Month", "Unemployment Rate")
y84<-cbind(Year= 1984 ,y84)
y84<-y84[-c(1,14),]
y84<-y84[order(match(y84$Month, month.abb)), ]
y84$Month<-factor(y84$Month, levels = month.abb)
```

```{r, echo=FALSE}

y85<-Unemp %>% 
  rownames_to_column() %>% 
  filter(Year == 1985 )%>%
  gather(variable, value, -rowname) %>% 
  spread(rowname, value)
colnames(y85) <- c("Month", "Unemployment Rate")
y85<-cbind(Year= 1985 ,y85)
y85<-y85[-c(1,14),]
y85<-y85[order(match(y85$Month, month.abb)), ]
y85$Month<-factor(y85$Month, levels = month.abb)
```

```{r, echo=FALSE}

y86<-Unemp %>% 
  rownames_to_column() %>% 
  filter(Year == 1986 )%>%
  gather(variable, value, -rowname) %>% 
  spread(rowname, value)
colnames(y86) <- c("Month", "Unemployment Rate")
y86<-cbind(Year= 1986 ,y86)
y86<-y86[-c(1,14),]
y86<-y86[order(match(y86$Month, month.abb)), ]
y86$Month<-factor(y86$Month, levels = month.abb)
```

```{r, echo=FALSE}

y87<-Unemp %>% 
  rownames_to_column() %>% 
  filter(Year == 1987 )%>%
  gather(variable, value, -rowname) %>% 
  spread(rowname, value)
colnames(y87) <- c("Month", "Unemployment Rate")
y87<-cbind(Year= 1987 ,y87)
y87<-y87[-c(1,14),]
y87<-y87[order(match(y87$Month, month.abb)), ]
y87$Month<-factor(y87$Month, levels = month.abb)
```

```{r, echo=FALSE}

y88<-Unemp %>% 
  rownames_to_column() %>% 
  filter(Year == 1988 )%>%
  gather(variable, value, -rowname) %>% 
  spread(rowname, value)
colnames(y88) <- c("Month", "Unemployment Rate")
y88<-cbind(Year= 1988 ,y88)
y88<-y88[-c(1,14),]
y88<-y88[order(match(y88$Month, month.abb)), ]
y88$Month<-factor(y88$Month, levels = month.abb)
```

```{r, echo=FALSE}

y89<-Unemp %>% 
  rownames_to_column() %>% 
  filter(Year == 1989 )%>%
  gather(variable, value, -rowname) %>% 
  spread(rowname, value)
colnames(y89) <- c("Month", "Unemployment Rate")
y89<-cbind(Year= 1989 ,y89)
y89<-y89[-c(1,14),]
y89<-y89[order(match(y89$Month, month.abb)), ]
y89$Month<-factor(y89$Month, levels = month.abb)
```

```{r, echo=FALSE}

y90<-Unemp %>% 
  rownames_to_column() %>% 
  filter(Year == 1990 )%>%
  gather(variable, value, -rowname) %>% 
  spread(rowname, value)
colnames(y90) <- c("Month", "Unemployment Rate")
y90<-cbind(Year= 1990 ,y90)
y90<-y90[-c(1,14),]
y90<-y90[order(match(y90$Month, month.abb)), ]
y90$Month<-factor(y90$Month, levels = month.abb)
```

```{r, echo=FALSE}

y91<-Unemp %>% 
  rownames_to_column() %>% 
  filter(Year == 1991 )%>%
  gather(variable, value, -rowname) %>% 
  spread(rowname, value)
colnames(y91) <- c("Month", "Unemployment Rate")
y91<-cbind(Year= 1991 ,y91)
y91<-y91[-c(1,14),]
y91<-y91[order(match(y91$Month, month.abb)), ]
y91$Month<-factor(y91$Month, levels = month.abb)
```

```{r, echo=FALSE}

y92<-Unemp %>% 
  rownames_to_column() %>% 
  filter(Year == 1992 )%>%
  gather(variable, value, -rowname) %>% 
  spread(rowname, value)
colnames(y92) <- c("Month", "Unemployment Rate")
y92<-cbind(Year= 1992 ,y92)
y92<-y92[-c(1,14),]
y92<-y92[order(match(y92$Month, month.abb)), ]
y92$Month<-factor(y92$Month, levels = month.abb)
```

```{r, echo=FALSE}

y93<-Unemp %>% 
  rownames_to_column() %>% 
  filter(Year == 1993 )%>%
  gather(variable, value, -rowname) %>% 
  spread(rowname, value)
colnames(y93) <- c("Month", "Unemployment Rate")
y93<-cbind(Year= 1993 ,y93)
y93<-y93[-c(1,14),]
y93<-y93[order(match(y93$Month, month.abb)), ]
y93$Month<-factor(y93$Month, levels = month.abb)
```

```{r, echo=FALSE}

y94<-Unemp %>% 
  rownames_to_column() %>% 
  filter(Year == 1994 )%>%
  gather(variable, value, -rowname) %>% 
  spread(rowname, value)
colnames(y94) <- c("Month", "Unemployment Rate")
y94<-cbind(Year= 1994 ,y94)
y94<-y94[-c(1,14),]
y94<-y94[order(match(y94$Month, month.abb)), ]
y94$Month<-factor(y94$Month, levels = month.abb)
```

```{r, echo=FALSE}

y95<-Unemp %>% 
  rownames_to_column() %>% 
  filter(Year == 1995 )%>%
  gather(variable, value, -rowname) %>% 
  spread(rowname, value)
colnames(y95) <- c("Month", "Unemployment Rate")
y95<-cbind(Year= 1995 ,y95)
y95<-y95[-c(1,14),]
y95<-y95[order(match(y95$Month, month.abb)), ]
y95$Month<-factor(y95$Month, levels = month.abb)
```

```{r, echo=FALSE}

y96<-Unemp %>% 
  rownames_to_column() %>% 
  filter(Year == 1996 )%>%
  gather(variable, value, -rowname) %>% 
  spread(rowname, value)
colnames(y96) <- c("Month", "Unemployment Rate")
y96<-cbind(Year= 1996 ,y96)
y96<-y96[-c(1,14),]
y96<-y96[order(match(y96$Month, month.abb)), ]
y96$Month<-factor(y96$Month, levels = month.abb)
```

```{r, echo=FALSE}

y97<-Unemp %>% 
  rownames_to_column() %>% 
  filter(Year == 1997 )%>%
  gather(variable, value, -rowname) %>% 
  spread(rowname, value)
colnames(y97) <- c("Month", "Unemployment Rate")
y97<-cbind(Year= 1997 ,y97)
y97<-y97[-c(1,14),]
y97<-y97[order(match(y97$Month, month.abb)), ]
y97$Month<-factor(y97$Month, levels = month.abb)
```

```{r, echo=FALSE}

y98<-Unemp %>% 
  rownames_to_column() %>% 
  filter(Year == 1998 )%>%
  gather(variable, value, -rowname) %>% 
  spread(rowname, value)
colnames(y98) <- c("Month", "Unemployment Rate")
y98<-cbind(Year= 1998 ,y98)
y98<-y98[-c(1,14),]
y98<-y98[order(match(y98$Month, month.abb)), ]
y98$Month<-factor(y98$Month, levels = month.abb)
```

```{r, echo=FALSE}

y99<-Unemp %>% 
  rownames_to_column() %>% 
  filter(Year == 1999 )%>%
  gather(variable, value, -rowname) %>% 
  spread(rowname, value)
colnames(y99) <- c("Month", "Unemployment Rate")
y99<-cbind(Year= 1999 ,y99)
y99<-y99[-c(1,14),]
y99<-y99[order(match(y99$Month, month.abb)), ]
y99$Month<-factor(y99$Month, levels = month.abb)
```

```{r, echo=FALSE}

y00<-Unemp %>% 
  rownames_to_column() %>% 
  filter(Year == 2000 )%>%
  gather(variable, value, -rowname) %>% 
  spread(rowname, value)
colnames(y00) <- c("Month", "Unemployment Rate")
y00<-cbind(Year= 2000 ,y00)
y00<-y00[-c(1,14),]
y00<-y00[order(match(y00$Month, month.abb)), ]
y00$Month<-factor(y00$Month, levels = month.abb)
```

```{r, echo=FALSE}

y01<-Unemp %>% 
  rownames_to_column() %>% 
  filter(Year == 2001 )%>%
  gather(variable, value, -rowname) %>% 
  spread(rowname, value)
colnames(y01) <- c("Month", "Unemployment Rate")
y01<-cbind(Year= 2001 ,y01)
y01<-y01[-c(1,14),]
y01<-y01[order(match(y01$Month, month.abb)), ]
y01$Month<-factor(y01$Month, levels = month.abb)
```

```{r, echo=FALSE}

y02<-Unemp %>% 
  rownames_to_column() %>% 
  filter(Year == 2002 )%>%
  gather(variable, value, -rowname) %>% 
  spread(rowname, value)
colnames(y02) <- c("Month", "Unemployment Rate")
y02<-cbind(Year= 2002 ,y02)
y02<-y02[-c(1,14),]
y02<-y02[order(match(y02$Month, month.abb)), ]
y02$Month<-factor(y02$Month, levels = month.abb)
```

```{r, echo=FALSE}

y03<-Unemp %>% 
  rownames_to_column() %>% 
  filter(Year == 2003 )%>%
  gather(variable, value, -rowname) %>% 
  spread(rowname, value)
colnames(y03) <- c("Month", "Unemployment Rate")
y03<-cbind(Year= 2003 ,y03)
y03<-y03[-c(1,14),]
y03<-y03[order(match(y03$Month, month.abb)), ]
y03$Month<-factor(y03$Month, levels = month.abb)
```

```{r, echo=FALSE}

y04<-Unemp %>% 
  rownames_to_column() %>% 
  filter(Year == 2004 )%>%
  gather(variable, value, -rowname) %>% 
  spread(rowname, value)
colnames(y04) <- c("Month", "Unemployment Rate")
y04<-cbind(Year= 2004 ,y04)
y04<-y04[-c(1,14),]
y04<-y04[order(match(y04$Month, month.abb)), ]
y04$Month<-factor(y04$Month, levels = month.abb)
```

```{r, echo=FALSE}

y05<-Unemp %>% 
  rownames_to_column() %>% 
  filter(Year == 2005 )%>%
  gather(variable, value, -rowname) %>% 
  spread(rowname, value)
colnames(y05) <- c("Month", "Unemployment Rate")
y05<-cbind(Year= 2005 ,y05)
y05<-y05[-c(1,14),]
y05<-y05[order(match(y05$Month, month.abb)), ]
y05$Month<-factor(y05$Month, levels = month.abb)
```

```{r, echo=FALSE}

y06<-Unemp %>% 
  rownames_to_column() %>% 
  filter(Year == 2006 )%>%
  gather(variable, value, -rowname) %>% 
  spread(rowname, value)
colnames(y06) <- c("Month", "Unemployment Rate")
y06<-cbind(Year= 2006 ,y06)
y06<-y06[-c(1,14),]
y06<-y06[order(match(y06$Month, month.abb)), ]
y06$Month<-factor(y06$Month, levels = month.abb)
```

```{r, echo=FALSE}

y07<-Unemp %>% 
  rownames_to_column() %>% 
  filter(Year == 2007 )%>%
  gather(variable, value, -rowname) %>% 
  spread(rowname, value)
colnames(y07) <- c("Month", "Unemployment Rate")
y07<-cbind(Year= 2007 ,y07)
y07<-y07[-c(1,14),]
y07<-y07[order(match(y07$Month, month.abb)), ]
y07$Month<-factor(y07$Month, levels = month.abb)
```

```{r, echo=FALSE}

y08<-Unemp %>% 
  rownames_to_column() %>% 
  filter(Year == 2008 )%>%
  gather(variable, value, -rowname) %>% 
  spread(rowname, value)
colnames(y08) <- c("Month", "Unemployment Rate")
y08<-cbind(Year= 2008 ,y08)
y08<-y08[-c(1,14),]
y08<-y08[order(match(y08$Month, month.abb)), ]
y08$Month<-factor(y08$Month, levels = month.abb)
```

```{r, echo=FALSE}

y09<-Unemp %>% 
  rownames_to_column() %>% 
  filter(Year == 2009 )%>%
  gather(variable, value, -rowname) %>% 
  spread(rowname, value)
colnames(y09) <- c("Month", "Unemployment Rate")
y09<-cbind(Year= 2009 ,y09)
y09<-y09[-c(1,14),]
y09<-y09[order(match(y09$Month, month.abb)), ]
y09$Month<-factor(y09$Month, levels = month.abb)
```

```{r, echo=FALSE}

y10<-Unemp %>% 
  rownames_to_column() %>% 
  filter(Year == 2010 )%>%
  gather(variable, value, -rowname) %>% 
  spread(rowname, value)
colnames(y10) <- c("Month", "Unemployment Rate")
y10<-cbind(Year= 2010 ,y10)
y10<-y10[-c(1,14),]
y10<-y10[order(match(y10$Month, month.abb)), ]
y10$Month<-factor(y10$Month, levels = month.abb)
```

```{r, echo=FALSE}

y11<-Unemp %>% 
  rownames_to_column() %>% 
  filter(Year == 2011 )%>%
  gather(variable, value, -rowname) %>% 
  spread(rowname, value)
colnames(y11) <- c("Month", "Unemployment Rate")
y11<-cbind(Year= 2011 ,y11)
y11<-y11[-c(1,14),]
y11<-y11[order(match(y11$Month, month.abb)), ]
y11$Month<-factor(y11$Month, levels = month.abb)
```

```{r, echo=FALSE}

y12<-Unemp %>% 
  rownames_to_column() %>% 
  filter(Year == 2012 )%>%
  gather(variable, value, -rowname) %>% 
  spread(rowname, value)
colnames(y12) <- c("Month", "Unemployment Rate")
y12<-cbind(Year= 2012 ,y12)
y12<-y12[-c(1,14),]
y12<-y12[order(match(y12$Month, month.abb)), ]
y12$Month<-factor(y12$Month, levels = month.abb)
```

```{r, echo=FALSE}

y13<-Unemp %>% 
  rownames_to_column() %>% 
  filter(Year == 2013 )%>%
  gather(variable, value, -rowname) %>% 
  spread(rowname, value)
colnames(y13) <- c("Month", "Unemployment Rate")
y13<-cbind(Year= 2013 ,y13)
y13<-y13[-c(1,14),]
y13<-y13[order(match(y13$Month, month.abb)), ]
y13$Month<-factor(y13$Month, levels = month.abb)
```

```{r, echo=FALSE}

y14<-Unemp %>% 
  rownames_to_column() %>% 
  filter(Year == 2014 )%>%
  gather(variable, value, -rowname) %>% 
  spread(rowname, value)
colnames(y14) <- c("Month", "Unemployment Rate")
y14<-cbind(Year= 2014 ,y14)
y14<-y14[-c(1,14),]
y14<-y14[order(match(y14$Month, month.abb)), ]
y14$Month<-factor(y14$Month, levels = month.abb)
```

```{r, echo=FALSE}

y15<-Unemp %>% 
  rownames_to_column() %>% 
  filter(Year == 2015 )%>%
  gather(variable, value, -rowname) %>% 
  spread(rowname, value)
colnames(y15) <- c("Month", "Unemployment Rate")
y15<-cbind(Year= 2015 ,y15)
y15<-y15[-c(1,14),]
y15<-y15[order(match(y15$Month, month.abb)), ]
y15$Month<-factor(y15$Month, levels = month.abb)
```

```{r, echo=FALSE}

y16<-Unemp %>% 
  rownames_to_column() %>% 
  filter(Year == 2016 )%>%
  gather(variable, value, -rowname) %>% 
  spread(rowname, value)
colnames(y16) <- c("Month", "Unemployment Rate")
y16<-cbind(Year= 2016 ,y16)
y16<-y16[-c(1,14),]
y16<-y16[order(match(y16$Month, month.abb)), ]
y16$Month<-factor(y16$Month, levels = month.abb)
```

```{r, echo=FALSE}

y17<-Unemp %>% 
  rownames_to_column() %>% 
  filter(Year == 2017 )%>%
  gather(variable, value, -rowname) %>% 
  spread(rowname, value)
colnames(y17) <- c("Month", "Unemployment Rate")
y17<-cbind(Year= 2017 ,y17)
y17<-y17[-c(1,14),]
y17<-y17[order(match(y17$Month, month.abb)), ]
y17$Month<-factor(y17$Month, levels = month.abb)
```

```{r, echo=FALSE}

y18<-Unemp %>% 
  rownames_to_column() %>% 
  filter(Year == 2018 )%>%
  gather(variable, value, -rowname) %>% 
  spread(rowname, value)
colnames(y18) <- c("Month", "Unemployment Rate")
y18<-cbind(Year= 2018 ,y18)
y18<-y18[-c(1,14),]
y18<-y18[order(match(y18$Month, month.abb)), ]
y18$Month<-factor(y18$Month, levels = month.abb)
```

```{r, echo=FALSE}

y19<-Unemp %>% 
  rownames_to_column() %>% 
  filter(Year == 2019 )%>%
  gather(variable, value, -rowname) %>% 
  spread(rowname, value)
colnames(y19) <- c("Month", "Unemployment Rate")
y19<-cbind(Year= 2019 ,y19)
y19<-y19[-c(1,14),]
y19<-y19[order(match(y19$Month, month.abb)), ]
y19$Month<-factor(y19$Month, levels = month.abb)
```




```{r,echo=FALSE}
p = ggplot() + 
  geom_line(data = y48, aes(x = Month, y = `Unemployment Rate`,group = Year,colour="blue")) +
  geom_line(data = y49, aes(x = Month, y = `Unemployment Rate`,group = Year,colour="red"))+
  geom_line(data = y50, aes(x = Month, y = `Unemployment Rate`,group = Year,colour="orange"))+
  geom_line(data = y51, aes(x = Month, y = `Unemployment Rate`,group = Year,colour="green"))+
  geom_line(data = y52, aes(x = Month, y = `Unemployment Rate`,group = Year,colour="firebrick"))+
  geom_line(data = y53, aes(x = Month, y = `Unemployment Rate`,group = Year,colour="yellow"))+
  geom_line(data = y54, aes(x = Month, y = `Unemployment Rate`,group = Year,colour="purple"))+
  geom_line(data = y55, aes(x = Month, y = `Unemployment Rate`,group = Year,colour="black"))+
  geom_line(data = y56, aes(x = Month, y = `Unemployment Rate`,group = Year,colour="chocolate"))+
  geom_line(data = y57, aes(x = Month, y = `Unemployment Rate`,group = Year,colour="red"))+
  geom_line(data = y58, aes(x = Month, y = `Unemployment Rate`,group = Year,colour="pink"))+
  geom_line(data = y59, aes(x = Month, y = `Unemployment Rate`,group = Year,colour="beige"))+
  geom_line(data = y60, aes(x = Month, y = `Unemployment Rate`,group = Year,colour="azure"))+
  geom_line(data = y61, aes(x = Month, y = `Unemployment Rate`,group = Year,colour="coral"))+
  geom_line(data = y62, aes(x = Month, y = `Unemployment Rate`,group = Year,colour="aquamarine2"))+
  geom_line(data = y63, aes(x = Month, y = `Unemployment Rate`,group = Year,colour="darkgoldenrod1"))+
  geom_line(data = y64, aes(x = Month, y = `Unemployment Rate`,group = Year,colour="bisque4"))+
  geom_line(data = y65, aes(x = Month, y = `Unemployment Rate`,group = Year,colour="bisque1"))+
  geom_line(data = y66, aes(x = Month, y = `Unemployment Rate`,group = Year,colour="azure4"))+
  geom_line(data = y67, aes(x = Month, y = `Unemployment Rate`,group = Year,colour="aquamarine4"))+
  geom_line(data = y68, aes(x = Month, y = `Unemployment Rate`,group = Year,colour="darkolivegreen"))+
  geom_line(data = y69, aes(x = Month, y = `Unemployment Rate`,group = Year,colour="darkolivegreen2"))+
  geom_line(data = y70, aes(x = Month, y = `Unemployment Rate`,group = Year,colour="darkgreen"))+
  geom_line(data = y71, aes(x = Month, y = `Unemployment Rate`,group = Year,colour="blue"))+
  geom_line(data = y72, aes(x = Month, y = `Unemployment Rate`,group = Year,colour="orange"))+
  geom_line(data = y73, aes(x = Month, y = `Unemployment Rate`,group = Year,colour="darkgreen"))+
  geom_line(data = y74, aes(x = Month, y = `Unemployment Rate`,group = Year,colour="black"))+
  geom_line(data = y75, aes(x = Month, y = `Unemployment Rate`,group = Year,colour="olive"))+
  geom_line(data = y76, aes(x = Month, y = `Unemployment Rate`,group = Year,colour="darkgreen"))+
  geom_line(data = y77, aes(x = Month, y = `Unemployment Rate`,group = Year,colour="aquamarine2"))+
  geom_line(data = y78, aes(x = Month, y = `Unemployment Rate`,group = Year,colour="bisque1"))+
  geom_line(data = y79, aes(x = Month, y = `Unemployment Rate`,group = Year,colour="beige"))+
  geom_line(data = y79, aes(x = Month, y = `Unemployment Rate`,group = Year,colour="azure"))+
  geom_line(data = y80, aes(x = Month, y = `Unemployment Rate`,group = Year,colour="aquamarine2"))+
  geom_line(data = y81, aes(x = Month, y = `Unemployment Rate`,group = Year,colour="bisque1"))+
  geom_line(data = y82, aes(x = Month, y = `Unemployment Rate`,group = Year,colour="chocolate"))+
  geom_line(data = y83, aes(x = Month, y = `Unemployment Rate`,group = Year,colour="darkgoldenrod1"))+
  geom_line(data = y84, aes(x = Month, y = `Unemployment Rate`,group = Year,colour="firebrick"))+
  geom_line(data = y85, aes(x = Month, y = `Unemployment Rate`,group = Year,colour="green"))+
  geom_line(data = y86, aes(x = Month, y = `Unemployment Rate`,group = Year,colour="yellow"))+
  geom_line(data = y87, aes(x = Month, y = `Unemployment Rate`,group = Year,colour="azure4"))+
  geom_line(data = y88, aes(x = Month, y = `Unemployment Rate`,group = Year,colour="blue"))+
  geom_line(data = y89, aes(x = Month, y = `Unemployment Rate`,group = Year,colour="pink"))+
  geom_line(data = y90, aes(x = Month, y = `Unemployment Rate`,group = Year,colour="purple"))+
  geom_line(data = y91, aes(x = Month, y = `Unemployment Rate`,group = Year,colour="sea green"))+
  geom_line(data = y92, aes(x = Month, y = `Unemployment Rate`,group = Year,colour="violet"))+
  geom_line(data = y93, aes(x = Month, y = `Unemployment Rate`,group = Year,colour="aquamarine3"))+
  geom_line(data = y94, aes(x = Month, y = `Unemployment Rate`,group = Year,colour="bisque3"))+
  geom_line(data = y95, aes(x = Month, y = `Unemployment Rate`,group = Year,colour="azure2"))+
  geom_line(data = y96, aes(x = Month, y = `Unemployment Rate`,group = Year,colour="azure3"))+
  geom_line(data = y97, aes(x = Month, y = `Unemployment Rate`,group = Year,colour="bisque2"))+
  geom_line(data = y98, aes(x = Month, y = `Unemployment Rate`,group = Year,colour="brown"))+
  geom_line(data = y99, aes(x = Month, y = `Unemployment Rate`,group = Year,colour="orange"))+
  geom_line(data = y00, aes(x = Month, y = `Unemployment Rate`,group = Year,colour="olive"))+
  geom_line(data = y01, aes(x = Month, y = `Unemployment Rate`,group = Year,colour="pink"))+
  geom_line(data = y02, aes(x = Month, y = `Unemployment Rate`,group = Year,colour="purple"))+
  geom_line(data = y03, aes(x = Month, y = `Unemployment Rate`,group = Year,colour="black"))+
  geom_line(data = y04, aes(x = Month, y = `Unemployment Rate`,group = Year,colour="brown"))+
  geom_line(data = y05, aes(x = Month, y = `Unemployment Rate`,group = Year,colour="bisque3"))+
  geom_line(data = y06, aes(x = Month, y = `Unemployment Rate`,group = Year,colour="blue"))+
  geom_line(data = y07, aes(x = Month, y = `Unemployment Rate`,group = Year,colour="coral"))+
  geom_line(data = y08, aes(x = Month, y = `Unemployment Rate`,group = Year,colour="darkgoldenrod1"))+
  geom_line(data = y09, aes(x = Month, y = `Unemployment Rate`,group = Year,colour="darkolivegreen"))+
  geom_line(data = y10, aes(x = Month, y = `Unemployment Rate`,group = Year,colour="darkgreen"))+
  geom_line(data = y11, aes(x = Month, y = `Unemployment Rate`,group = Year,colour="firebrick"))+
  geom_line(data = y12, aes(x = Month, y = `Unemployment Rate`,group = Year,colour="red"))+
  geom_line(data = y13, aes(x = Month, y = `Unemployment Rate`,group = Year,colour="green"))+
  geom_line(data = y14, aes(x = Month, y = `Unemployment Rate`,group = Year,colour="sea green"))+
  geom_line(data = y16, aes(x = Month, y = `Unemployment Rate`,group = Year,colour="aquamarine2"))+
  geom_line(data = y17, aes(x = Month, y = `Unemployment Rate`,group = Year,colour="orange"))+
  geom_line(data = y18, aes(x = Month, y = `Unemployment Rate`,group = Year,colour="olive"))+
  geom_line(data = y19, aes(x = Month, y = `Unemployment Rate`,group = Year,colour="aquamarine1"))+
  scale_color_discrete(name = "Years", labels = c("1948", "1949","1950","1951","1952","1953",
  "1954","1955","1956","1957","1958","1959","1960","1961","1962","1963","1964","1965","1966",
  "1967","1968","1969","1970", "1971", "1972", "1973", "1974", "1975","1976", "1977", "1978",
  "1979", "1980","1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990",
  "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002",
  "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014",
  "2015", "2016", "2017", "2018", "2019"))+ scale_x_discrete(limits = month.abb)
print(p)

     

```

```{r,echo=FALSE,include= FALSE}


p = ggplot() + 
  geom_line(data = y48, aes(x = Month, y = `Unemployment Rate`,group = Year,colour="blue")) +
  geom_line(data = y49, aes(x = Month, y = `Unemployment Rate`,group = Year,colour="red"))+
  geom_line(data = y50, aes(x = Month, y = `Unemployment Rate`,group = Year,colour="orange"))+
  geom_line(data = y51, aes(x = Month, y = `Unemployment Rate`,group = Year,colour="green"))+
  scale_color_discrete(name = "Years", labels = c("1948", "1949","1950","1951"))+ scale_x_discrete(limits = month.abb)

print(p)
```

